<?php

return [
    'api.prefix' => [
        'key' => 'mxheadless.api.prefix',
        'xtype' => 'textfield',
        'value' => '/api',
        'area' => 'mxheadless_api',
    ],
    'debug' => [
        'key' => 'mxheadless.debug',
        'xtype' => 'combo-boolean',
        'value' => false,
        'area' => 'mxheadless_main',
    ],
    'enabled' => [
        'key' => 'mxheadless.enabled',
        'xtype' => 'combo-boolean',
        'value' => true,
        'area' => 'mxheadless_main',
    ],
    'cache.enabled' => [
        'key' => 'mxheadless.cache.enabled',
        'xtype' => 'combo-boolean',
        'value' => true,
        'area' => 'mxheadless_cache',
    ],
    'cache_ttl' => [
        'key' => 'mxheadless.cache_ttl',
        'xtype' => 'numberfield',
        'value' => 300,
        'area' => 'mxheadless_cache',
    ],
    'rate_limit.enabled' => [
        'key' => 'mxheadless.rate_limit.enabled',
        'xtype' => 'combo-boolean',
        'value' => true,
        'area' => 'mxheadless_rate_limit',
    ],
    'rate_limit.max_requests' => [
        'key' => 'mxheadless.rate_limit.max_requests',
        'xtype' => 'numberfield',
        'value' => 120,
        'area' => 'mxheadless_rate_limit',
    ],
    'rate_limit.window_seconds' => [
        'key' => 'mxheadless.rate_limit.window_seconds',
        'xtype' => 'numberfield',
        'value' => 60,
        'area' => 'mxheadless_rate_limit',
    ],
    'cors.enabled' => [
        'key' => 'mxheadless.cors.enabled',
        'xtype' => 'combo-boolean',
        'value' => false,
        'area' => 'mxheadless_cors',
    ],
    'cors.allowed_origins' => [
        'key' => 'mxheadless.cors.allowed_origins',
        'xtype' => 'textarea',
        'value' => '',
        'area' => 'mxheadless_cors',
    ],
    'cors.allowed_methods' => [
        'key' => 'mxheadless.cors.allowed_methods',
        'xtype' => 'textfield',
        'value' => 'GET,POST,PUT,PATCH,DELETE,OPTIONS',
        'area' => 'mxheadless_cors',
    ],
    'cors.allowed_headers' => [
        'key' => 'mxheadless.cors.allowed_headers',
        'xtype' => 'textfield',
        'value' => 'Authorization,Content-Type,X-Request-ID,X-CSRF-Token,X-Context,X-API-Key,Idempotency-Key',
        'area' => 'mxheadless_cors',
    ],
    'cors.expose_headers' => [
        'key' => 'mxheadless.cors.expose_headers',
        'xtype' => 'textfield',
        'value' => 'ETag,X-Request-ID,X-RateLimit-Limit,X-RateLimit-Remaining,X-RateLimit-Reset,Idempotency-Replayed',
        'area' => 'mxheadless_cors',
    ],
    'cors.allow_credentials' => [
        'key' => 'mxheadless.cors.allow_credentials',
        'xtype' => 'combo-boolean',
        'value' => false,
        'area' => 'mxheadless_cors',
    ],
    'max_body_bytes' => [
        'key' => 'mxheadless.max_body_bytes',
        'xtype' => 'numberfield',
        'value' => 1048576,
        'area' => 'mxheadless_security',
    ],
    'max_uri_bytes' => [
        'key' => 'mxheadless.max_uri_bytes',
        'xtype' => 'numberfield',
        'value' => 2048,
        'area' => 'mxheadless_security',
    ],
    'trusted_proxies' => [
        'key' => 'mxheadless.trusted_proxies',
        'xtype' => 'textarea',
        'value' => '',
        'area' => 'mxheadless_security',
    ],
    'idempotency.enabled' => [
        'key' => 'mxheadless.idempotency.enabled',
        'xtype' => 'combo-boolean',
        'value' => true,
        'area' => 'mxheadless_security',
    ],
    'idempotency_ttl' => [
        'key' => 'mxheadless.idempotency_ttl',
        'xtype' => 'numberfield',
        'value' => 86400,
        'area' => 'mxheadless_security',
    ],
    'webhook.max_attempts' => [
        'key' => 'mxheadless.webhook.max_attempts',
        'xtype' => 'numberfield',
        'value' => 5,
        'area' => 'mxheadless_webhooks',
    ],
    'webhook.worker_limit' => [
        'key' => 'mxheadless.webhook.worker_limit',
        'xtype' => 'numberfield',
        'value' => 50,
        'area' => 'mxheadless_webhooks',
    ],
    'webhook.allow_private_urls' => [
        'key' => 'mxheadless.webhook.allow_private_urls',
        'xtype' => 'combo-boolean',
        'value' => false,
        'area' => 'mxheadless_webhooks',
    ],
    'audit.enabled' => [
        'key' => 'mxheadless.audit.enabled',
        'xtype' => 'combo-boolean',
        'value' => false,
        'area' => 'mxheadless_audit',
    ],
    'audit.retention_days' => [
        'key' => 'mxheadless.audit.retention_days',
        'xtype' => 'numberfield',
        'value' => 90,
        'area' => 'mxheadless_audit',
    ],
    'audit.log_get' => [
        'key' => 'mxheadless.audit.log_get',
        'xtype' => 'combo-boolean',
        'value' => false,
        'area' => 'mxheadless_audit',
    ],
    'oauth.enabled' => [
        'key' => 'mxheadless.oauth.enabled',
        'xtype' => 'combo-boolean',
        'value' => false,
        'area' => 'mxheadless_oauth',
    ],
    'oauth.token_ttl' => [
        'key' => 'mxheadless.oauth.token_ttl',
        'xtype' => 'numberfield',
        'value' => 3600,
        'area' => 'mxheadless_oauth',
    ],
    'oauth.password_grant_enabled' => [
        'key' => 'mxheadless.oauth.password_grant_enabled',
        'xtype' => 'combo-boolean',
        'value' => false,
        'area' => 'mxheadless_oauth',
    ],
];
